/**
 * Shopier webhook outcome codes — logs/API için (secret/payload içermez).
 */

export const SHOPIER_WEBHOOK_REASONS = {
  SUCCESS: 'SUCCESS',
  DUPLICATE_ORDER: 'DUPLICATE_ORDER',
  MISSING_WEBHOOK_SECRET: 'MISSING_WEBHOOK_SECRET',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  MISSING_EMAIL: 'MISSING_EMAIL',
  IGNORED_STATUS: 'IGNORED_STATUS',
  IGNORED_EVENT: 'IGNORED_EVENT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  ACTIVATION_FAILED: 'ACTIVATION_FAILED',
} as const;

export type ShopierWebhookReason =
  (typeof SHOPIER_WEBHOOK_REASONS)[keyof typeof SHOPIER_WEBHOOK_REASONS];
